export enum CanvasActions {
    NONE,
    MOVING_STATE,
    MOVING_CANVAS,
    CREATING_TRANSITION,
    CREATING_SELECTION,
    RESIZING_TRANSITION,
    MOVING_NOTE,
    RESIZING_NOTE,
    ANIMATING,
}