/* Dark Theme */
export const CanvasColors = {
    BACKGROUND: "#212529",

    // State
    DEFAULT_STATE: "#FF6D00",
    DEFAULT_STATE_SECONDARY: "#FF9100", 
    CLICKED_STATE: "#0b63de", 
    CLICKED_STATE_SECONDARY: "#4b9cf9",
    SIMULATION_STEP_STATE: "#eb022f", 
    SIMULATION_STEP_STATE_SECONDARY: "#ff385f",

    // Transition
    DEFAULT_TRANSITION: "#495057",
    DEFAULT_TRANSITION_TEXT: "#E9ECEF",
    CLICKED_TRANSITION: "#4b9cf9", 
    CLICKED_TRANSITION_TEXT: "#E9ECEF",
    SIMULATION_STEP_TRANSITION: "#ff385f", 
    SIMULATION_STEP_TRANSITION_TEXT: "#E9ECEF",

    // Selecion
    SELECTION: "#495057" + '55',
    SELECTION_BORDER: "#495057" + 'AA',

    // Notes
    NOTES: "#495057" + '55',
    NOTES_SECONDARY: "#495057",
    NOTES_TEXT: "#E9ECEF",
    NOTES_CLICKED: "#0b63de",
    NOTES_CLICKED_SECONDARY: "#4b9cf9",
    NOTES_CLICKED_TEXT: "#E9ECEF",

    // Other
    INFO_SUCCESS: "#00C853",
    INFO_WARNING: "#FFD600",
    INFO_ERROR: "#eb022f",
};
